[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=ToyBNB"
testpaths = [
    "tests",
]

[tool.black]
line-length = 160